// POST /api/user/assistant/chat  { message, sessionId }
// This function handles when the patient sends a message to the AI.
export const chat = async (req, res) => {

    // get and clea the patient's message
    const message = String(req.body.message || "").trim().slice(0, 1000); // limit is 1000 charctors
    const sessionId = String(req.body.sessionId || "").slice(0, 64);
    if (!message) return res.json({ success: false, message: "Empty message" });

    //Build the request body

    //This makes the conversation session associated with the authenticated patient  this is Why combine userId with sessionId 
    const body = JSON.stringify({ userId: req.userId, sessionId: `${req.userId}:${sessionId}`, message });

    const ts = Date.now().toString(); // going to use it when creating the HMAC signature.

    //This request was generated by someone who knows the shared DocOp secret.
    //Without this, somebody who discovers your n8n webhook URL could potentially send:
    const signature = crypto.createHmac("sha256", process.env.DOCOP_WEBHOOK_SECRET).update(`${ts}.${body}`).digest("hex");

    // send the request to n8n
    try {
        const r = await fetch(process.env.N8N_ASSISTANT_URL, {
            method: "POST",
            headers: { "Content-Type": "application/json", "x-docop-timestamp": ts, "x-docop-signature": signature },
            body, signal: AbortSignal.timeout(30000),  // 30s timeout do not wait forever
        });

        // check whether the n8n responde succesfully 
        if (!r.ok) throw new Error(`assistant HTTP ${r.status}`);
        // get the AI response
        const { reply } = await r.json();

        // check whether there is a pending booking
        const pending = await pendingBookingModel.findOne({
            userId: req.userId, status: "pending",
            expiresAt: { $gt: new Date() }
        }).lean();
        res.json({
            success: true, reply, pendingBooking: pending && {
                id: pending._id,
                doctorName: pending.doctorName, date: pending.slotDate, time: pending.slotTime, fee: pending.fee
            }
        });
    } catch (err) {
        console.error("[assistant]", err.message);
        res.json({ success: false, message: "The assistant is unavailable right now. You can still book from the Doctors page." });
        //This is called graceful failure.Your entire appointment system doesn't become unavailable just because the AI assistant is down.That's a very good production design.
    }
};

// POST /api/user/assistant/bookings/:id/confirm

// when the patient presses confirm 
export const confirmBooking = async (req, res) => {
    //Validate the pending booking ID
    if (!mongoose.isValidObjectId(req.params.id)) return res.json({ success: false, message: "Bad id" });

    //Find AND confirm the pending booking atomically
    //Find this exact pending booking, but only if it belongs to this patient, is still pending, and hasn't expired. If all conditions are true, change it to confirmed.
    const p = await pendingBookingModel.findOneAndUpdate(
        { _id: req.params.id, userId: req.userId, status: "pending", expiresAt: { $gt: new Date() } },
        { status: "confirmed" });

    //Handle expired/missing booking
    if (!p) return res.json({ success: false, message: "This booking request expired. Please ask again." });

    //Now create the REAL appointment
    const result = await createBooking({ userId: req.userId, docId: p.docId, slotDate: p.slotDate, slotTime: p.slotTime });
    //This solves a race condition The final booking must still go through the real atomic slot reservation.

    if (!result.success) await pendingBookingModel.updateOne({ _id: p._id }, { status: "cancelled" });
    res.json(result);
};

// POST /api/user/assistant/bookings/:id/cancel
//is used when the patient presses:

export const cancelPending = async (req, res) => {
    await pendingBookingModel.updateOne({ _id: req.params.id, userId: req.userId, status: "pending" }, { status: "cancelled" });
    res.json({ success: true });
};