server {
     listen 80;
      root /usr/share/nginx/html; 
      index index.html;

# React Router: unknown paths go to index.html
location / { 
    try_files $uri $uri/ /index.html;
     }

# cache hashed JS/CSS files for a long time

location /assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";

}


}